type linenum = int

type token = 
  | TYPE of (Lexing.position)
  | VAR of (Lexing.position)
  | FUNCTION of (Lexing.position)
  | BREAK of (Lexing.position)
  | OF of (Lexing.position)
  | END of (Lexing.position)
  | IN of (Lexing.position)
  | NIL of (Lexing.position)
  | LET of (Lexing.position)
  | DO of (Lexing.position)
  | TO of (Lexing.position)
  | FOR of (Lexing.position)
  | WHILE of (Lexing.position)
  | ELSE of (Lexing.position)
  | THEN of (Lexing.position)
  | IF of (Lexing.position)
  | ARRAY of (Lexing.position)
  | ASSIGN of (Lexing.position)
  | OR of (Lexing.position)
  | AND of (Lexing.position)
  | GE of (Lexing.position)
  | GT of (Lexing.position)
  | LE of (Lexing.position)
  | LT of (Lexing.position)
  | NEQ of (Lexing.position)
  | EQ of (Lexing.position)
  | DIVIDE of (Lexing.position)
  | TIMES of (Lexing.position)
  | MINUS of (Lexing.position)
  | PLUS of (Lexing.position)
  | DOT of (Lexing.position)
  | RBRACE of (Lexing.position)
  | LBRACE of (Lexing.position)
  | RBRACK of (Lexing.position)
  | LBRACK of (Lexing.position)
  | RPAREN of (Lexing.position)
  | LPAREN of (Lexing.position)
  | SEMICOLON of (Lexing.position)
  | COLON of (Lexing.position)
  | COMMA of (Lexing.position)
  | STRING of ( (string) *  Lexing.position)
  | INT of ( (int) *  Lexing.position)
  | ID of ( (string) *  Lexing.position)
  | EOF of (Lexing.position)

